spring.application.name=OEP
spring.datasource.url=jdbc:mysql://localhost:3306/mcq_app
spring.datasource.username=root
spring.datasource.password=09peb310

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=5001